In [1]:
#function to write in csv
import csv
def write_list_in_file(final, name):
    with open(name, "w", newline="",encoding="utf8") as fp:
        a = csv.writer(fp, delimiter=',')
        a.writerows(final)


In [2]:
#Function to read csv files
from csv import reader
# Load a CSV file\n",
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
    return dataset


In [14]:
data = load_csv('season1.csv')

In [15]:
#print(data[1:])

In [16]:
import numpy as np
from sklearn.cluster import KMeans
    
X = np.array(data[1:])

cluster_num = 3

kmeans = KMeans(n_clusters=cluster_num)
kmeans.fit(X)

centroids = kmeans.cluster_centers_
labels = kmeans.labels_
    
print(kmeans.cluster_centers_)
print(kmeans.inertia_)

[[ 0.31731571  0.32117916  0.75579611  0.17903213]
 [ 0.22309403  0.22124276  0.494288    0.22564246]
 [ 0.40147874  0.3956713   0.49023674  0.24610212]]
4.41116355823
