In [1]:
#function to write in csv
import csv
def write_list_in_file(final, name):
    with open(name, "w", newline="",encoding="utf8") as fp:
        a = csv.writer(fp, delimiter=',')
        a.writerows(final)


In [2]:
#Function to read csv files
from csv import reader
# Load a CSV file\n",
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
    return dataset


In [3]:
#learn centers from source/base model
import numpy as np
from sklearn.cluster import KMeans

base_data = load_csv('season1.csv')    
X = np.array(base_data[1:])

cluster_num = 3

kmeans = KMeans(n_clusters=cluster_num)
kmeans.fit(X)

base_centroids = kmeans.cluster_centers_
#labels = kmeans.labels_
    
print(kmeans.cluster_centers_)
print(kmeans.inertia_)

[[ 0.31731571  0.32117916  0.75579611  0.17903213]
 [ 0.40147874  0.3956713   0.49023674  0.24610212]
 [ 0.22309403  0.22124276  0.494288    0.22564246]]
4.41116355823


In [5]:
#no of elements and load target data
elements = [10,20,30,40,50]
target_data = load_csv('season2.csv')

In [8]:
#base model results
X = np.array(target_data[1:])
kmeans = KMeans(n_clusters=cluster_num, init=base_centroids, max_iter=1)
kmeans.fit(X)
print(kmeans.inertia_)

5.94758665577


/home/tonmoy/anaconda3/lib/python3.6/site-packages/sklearn/cluster/k_means_.py:889: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


In [6]:
#retraining results
retrained_centroids= []

for n in elements:

    X = np.array(target_data[1:n+1])
    kmeans = KMeans(n_clusters=cluster_num)
    kmeans.fit(X)

    retrained_centroids.append(kmeans.cluster_centers_)
    #labels = kmeans.labels_

    #print(kmeans.cluster_centers_)
    #print(kmeans.inertia_)
    X = np.array(target_data[1:])
    kmeans = KMeans(n_clusters=cluster_num, init=kmeans.cluster_centers_, max_iter=1)
    kmeans.fit(X)

    #target_centroids = kmeans.cluster_centers_
    #labels = kmeans.labels_

    #print(kmeans.cluster_centers_)
    print(kmeans.inertia_)

5.38536744831
5.84911458257
5.16298416317
4.82748331856
4.7602860273


/home/tonmoy/anaconda3/lib/python3.6/site-packages/sklearn/cluster/k_means_.py:889: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)
